- name: set time zone
  file: 
    src: /usr/share/zoneinfo/{{ ntp_timezone }}
    dest: /etc/localtime
    state: link
    force: yes

- name: install NTP daemon
  yum:
    name: ntp
    state: installed

- name: ensure ntp daemon starts
  service:
    name: ntpd 
    state: started
    enabled: yes
  when: ntp_enabled
